### ISSUE TITLE
除了 config.toml，其它地方统一用 YAML

### ISSUE THREAD

**Issue by yihui** [HuaiyuZhang/rnorm.org#4]
比如

```
+++
title = "Contact"
id = "contact"
+++
```

改成

```yaml
---
title: "Contact"
id: "contact"
---
```
